[package]
name = "presence-rpc"
version = "0.0.2"
edition = "2024"
authors = ["seasnail1"]
license = "Apache-2.0"
description = "A minimal implementation of discord rich presence"
documentation = "https://docs.rs/bitflags"
homepage = "https://gitlab.com/seasnail1/presence-rpc"
repository = "https://gitlab.com/seasnail1/presence-rpc"
keywords = ["rich-presence", "rpc"]
exclude = [".*"]
readme = "README.md"

[dependencies]
flume = { version = "0.12.0", default-features = false }
nanoserde = {version = "0.2.1", default-features = false, features = ["std", "json"]}
thiserror = { version = "2.0.20", default-features = false }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
